// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { useModel } from '../model';
import { AccessContext } from './context';
import {useAppData} from '../appData'

export function Provider(props) {
    const { initialState } = useModel('@@initialState');
    const access = React.useMemo(() => {
        if (typeof useAppData().umiConfig.access=="function") {
            return useAppData().umiConfig.access(initialState)
        }
        return useAppData().umiConfig.access
    }, [initialState]);
    return (
        <AccessContext.Provider value={access}>
            { props.children }
            </AccessContext.Provider>
    );
}

export function accessProvider(container) {
    return <Provider>{ container }</Provider>;
}
