// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React  from 'react';
import { Provider } from './model';
<%
var models = $imports.ListSystemModels()
for(var i=0;i<models.length;i++){
    print(`import model_${i} from './models/${models[i]}'`)
}
%>
export const rawModels = {
    <%
    for(var i=0;i<models.length;i++){
          print(`model_${i}: { namespace: '${models[i]}', model: model_${i} },`)
    }
    %>
}


export function ModelProviderWrapper(props: any) {
    const models = React.useMemo(() => {
        return Object.keys(rawModels).reduce((memo, key) => {
            memo[rawModels[key].namespace] = rawModels[key].model;
            return memo;
        }, {});
    }, []);
    return <Provider models={models} {...props}>{ props.children }</Provider>
}

